version: '3.3'

services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'store'
      MYSQL_PASSWORD: 'senha-mysql'
      MYSQL_ROOT_PASSWORD: 'senha-mysql'
      DATABASE_URL: mysql://root:senha-mysql@db:4406/store
    ports:
      - '4406:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  my-db: